# Generated by Django 4.0.4 on 2022-05-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MEN', 'MEN'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='Male', max_length=10),
        ),
    ]
