# Generated by Django 4.0.4 on 2022-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address_idd',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
