# Generated by Django 4.0.4 on 2022-06-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_address_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
