# Generated by Django 4.0.4 on 2022-06-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_wallet_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referel_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
