# Generated by Django 4.0.4 on 2022-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_referel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referel_activated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
