# Generated by Django 4.0.4 on 2022-06-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_perc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
