# Generated by Django 4.0.4 on 2022-06-09 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
