# Generated by Django 4.0.4 on 2022-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Is_offer_active',
            field=models.BooleanField(default=True),
        ),
    ]
