# Generated by Django 4.0.4 on 2022-06-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
