# Generated by Django 4.0.4 on 2022-06-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_perc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
