# Generated by Django 4.0.4 on 2022-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_offer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
