# Generated by Django 4.0.4 on 2022-06-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_category_offer_active_category_offer_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_offer',
            old_name='isactive',
            new_name='active',
        ),
    ]
