# Generated by Django 4.0.4 on 2022-05-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='carts_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
