# Generated by Django 4.0.4 on 2022-06-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='coupon_applied',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
