# Generated by Django 4.0.4 on 2022-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_carts_coupon_applied_cartitem_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='coupon_applied',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
