# Generated by Django 4.0.4 on 2022-06-07 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0006_alter_cartitem_coupon_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon_applied',
        ),
        migrations.AddField(
            model_name='carts',
            name='coupon_applied',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
