# Generated by Django 4.0.4 on 2022-06-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cartitem_coupon_applied_carts_coupon_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='coupon_applied',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='coupon_applied',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
