# Generated by Django 4.0.4 on 2022-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_coupon_valid_from_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
