# Generated by Django 4.0.4 on 2022-06-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_final_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='final_offer_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
