# Generated by Django 4.0.4 on 2022-06-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cartitem_coupon_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
