# Generated by Django 4.0.4 on 2022-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_carts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
