# Generated by Django 4.0.4 on 2022-06-16 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0016_alter_cartitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentrazor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('payment_signature', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('FAILED', 'FAILED')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
