# Generated by Django 4.0.4 on 2022-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
