# Generated by Django 4.0.4 on 2022-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_ud_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ud_at',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
